### ISSUE TITLE
I don't know how to change player color

### ISSUE THREAD

**Issue by toga6930** [slash9494/react-modern-audio-player#16]
I wanna change css of player but I don't know about react-spectrum.. I can't understand readme file also. How can I change background color?

**Comment by slash9494** [comment]
Hi @toga6930,

In **v2.0.0**, theming is fully supported via CSS custom properties. You can override any of these variables to customize the player:

```css
.rmap-player-provider {
  --rm-audio-player-text-color: #2c2c2c;
  --rm-audio-player-interface-container: #f5f5f5;    /* background color */
  --rm-audio-player-progress-bar: #0072f5;           /* progress bar color */
  --rm-audio-player-volume-thumb: #5c5c5c;
  --rm-audio-player-volume-fill: rgba(0, 0, 0, 0.5);
  --rm-audio-player-sortable-list: #eaeaea;
  /* ... and more */
}
```

For dark/light mode, use the `colorScheme` prop:

```tsx
<AudioPlayer playList={playList} colorScheme="dark" />
```

The player also automatically follows the OS `prefers-color-scheme` media query.

Full list of CSS variables: [`src/styles/vars.css`](https://github.com/slash9494/react-modern-audio-player/blob/main/package/src/styles/vars.css)

Closing as answered — feel free to reopen if you need more help!
